# -*- coding: utf-8 -*-
"""ProxyMed Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13V5a5jA1pbX6FcYLyMU0fCpWQIymKEw_
"""

import os
os.environ["OPENAI_API_KEY"] = "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"
# Replace with your actual API key

!pip install -U langchain-chroma

!pip install langchain-experimental

!pip install llama-index llama-index-core llama-index-llms-openai llama-index-embeddings-openai llama-index-vector-stores-chroma chromadb openai pandas flask

!pip install os-sys
!pip install datetime
!pip install tkinter
!pip install gradio
!pip install spacy
!pip install pymongo
!pip install fuzzywuzzy
!pip install nltk
!pip install python-Levenshtein
!pip install cohere
!pip install cohere-python
!pip install lark
!pip install lark-parser
 # Required for fuzzywuzzy

import os
import datetime
import tkinter as tk
from tkinter import scrolledtext
import gradio as gr
import spacy
from pymongo import MongoClient
from fuzzywuzzy import process
from nltk.tokenize import word_tokenize

def initialise_mongo_cloud_db_client():
    """
    Initializes a MongoDB client to connect to a MongoDB server in the cloud.

    This function reads environment variables to obtain the public IP address of the MongoDB server,
    the MongoDB server's username, and the MongoDB server's password. It then creates a connection
    string and establishes a connection to the MongoDB server using the PyMongo library.

    Returns:
        MongoClient: A connected MongoDB client.

    Raises:
        ValueError: If any of the required environment variables are not set.
    """

    # Read environment variables *** later we will read from env variables
    mongo_server_public_ip_address='37.27.209.22'
    mongodb_server_username='proxymd'
    mongodb_server_password='proxymd2025'

    # # Print the environment variables (optional)
    # print(f"MongoDB Server IP: {mongo_server_public_ip_address}")
    # print(f"MongoDB Username: {mongodb_server_username}")
    # print("MongoDB Password: [Hidden]")

    # Create the MongoDB connection string
    CONNECTION_STRING = "mongodb://%s:%s@%s:27017/" % (mongodb_server_username, mongodb_server_password, mongo_server_public_ip_address)

    # Establish a connection to the MongoDB server
    client = MongoClient(CONNECTION_STRING)

    return client

client = initialise_mongo_cloud_db_client()

client

from pymongo import MongoClient
from functools import lru_cache
import json

def initialise_mongo_cloud_db_client():
    """
    Initializes and returns a MongoDB client.
    Replace the connection string with your actual MongoDB URI.
    """
    CONNECTION_STRING = "mongodb://proxymd:proxymd2025@37.27.209.22:27017/"
    return MongoClient(CONNECTION_STRING)

@lru_cache(maxsize=1)
def fetch_and_cache_disease_symptoms():
    """
    Fetches, formats, and saves disease and symptom data from MongoDB to a JSON file.
    Returns the file path.
    """
    client = initialise_mongo_cloud_db_client()
    db = client["ProxyMedicineDB"]

    symptoms_collection = db["Symptoms"]
    diseases_collection = db["Diseases"]

    formatted_symptoms = {}
    formatted_diseases = {}

    # Fetch and format all symptoms data under each ID
    for symptom_document in symptoms_collection.find():
        doc_id = str(symptom_document.get("_id", "Unknown_ID"))  # Convert ObjectId to string
        symptom_document["_id"] = doc_id  # Replace ObjectId with string for JSON compatibility
        formatted_symptoms[doc_id] = symptom_document  # Store entire document as is

    # Fetch and format all diseases data under each ID
    for disease_document in diseases_collection.find():
        doc_id = str(disease_document.get("_id", "Unknown_ID"))  # Convert ObjectId to string
        disease_document["_id"] = doc_id  # Replace ObjectId with string for JSON compatibility
        formatted_diseases[doc_id] = disease_document  # Store entire document as is

    # Create a structured dictionary
    data = {
        "symptoms": formatted_symptoms,
        "diseases": formatted_diseases
    }

    # Save to a JSON file
    file_path = "disease_symptoms_data.json"
    with open(file_path, "w", encoding="utf-8") as json_file:
        json.dump(data, json_file, indent=4, ensure_ascii=False)

    print(f"Data successfully saved to {file_path}")
    return file_path

# Example usage
file_path = fetch_and_cache_disease_symptoms()
print(f"Download the file here: {file_path}")

import json
import csv

def extract_diseases_and_symptoms(json_file_path, diseases_csv_path, symptoms_csv_path):
    """
    Extracts disease and symptom information from a JSON file and saves them
    into separate CSV files.

    Args:
        json_file_path (str): Path to the input JSON file.
        diseases_csv_path (str): Path to the output CSV file for diseases.
        symptoms_csv_path (str): Path to the output CSV file for symptoms.
    """

    try:
        with open(json_file_path, 'r') as json_file:
            data = json.load(json_file)
    except FileNotFoundError:
        print(f"Error: JSON file not found at {json_file_path}")
        return
    except json.JSONDecodeError:
        print(f"Error: Invalid JSON format in {json_file_path}")
        return

    symptoms_data = data.get("symptoms")
    if not symptoms_data:
        print("Error: 'symptoms' key not found in JSON data.")
        return

    # --- Prepare and Write Diseases CSV ---
    disease_header = ["_id", "disease_name"]
    try:
        with open(diseases_csv_path, 'w', newline='', encoding='utf-8') as diseases_csv_file:
            disease_writer = csv.writer(diseases_csv_file)
            disease_writer.writerow(disease_header)

            for symptom_id, symptom_info in symptoms_data.items():
                # For conditions nested inside symptoms info
                if "conditions" in symptom_info and isinstance(symptom_info["conditions"], list):
                    for condition in symptom_info["conditions"]:
                        disease_name = condition.get("name", "")
                        disease_writer.writerow([symptom_info["_id"], disease_name])
                else: # standard format for the conditions
                    condition_data = symptom_info.get("condition")
                    if condition_data:
                         disease_name = condition_data.get("name", "")
                         disease_writer.writerow([symptom_info["_id"], disease_name])

    except Exception as e:
        print(f"An error occurred during diseases CSV writing: {e}")
        return

    # --- Prepare and Write Symptoms CSV ---
    symptom_header = ["_id", "disease_name", "symptom", "description"]
    try:
        with open(symptoms_csv_path, 'w', newline='', encoding='utf-8') as symptoms_csv_file:
            symptom_writer = csv.writer(symptoms_csv_file)
            symptom_writer.writerow(symptom_header)

            for symptom_id, symptom_info in symptoms_data.items():
                #standard format for the conditions
                condition_data = symptom_info.get("condition")
                if condition_data:
                    disease_name = condition_data.get("name", "")

                    # Handle the case where 'symptoms' is a list of dictionaries (Pharyngitis)
                    if "symptoms" in condition_data and isinstance(condition_data["symptoms"], list):
                        for symptom_entry in condition_data["symptoms"]:
                            symptom = symptom_entry.get("symptom", "")
                            description = symptom_entry.get("description", "")
                            symptom_writer.writerow([symptom_info["_id"], disease_name, symptom, description])

                    # Handle the case where 'Primary_Symptoms' is a list of dictionaries (Pharyngitis (Non-Strep))
                    elif "Primary_Symptoms" in condition_data and isinstance(condition_data["Primary_Symptoms"], list):
                        for symptom_entry in condition_data["Primary_Symptoms"]:
                            symptom = symptom_entry.get("Symptom", "")
                            description = symptom_entry.get("Description", "")
                            symptom_writer.writerow([symptom_info["_id"], disease_name, symptom, description])
                #For conditions nested inside symptoms info
                elif "conditions" in symptom_info and isinstance(symptom_info["conditions"], list):
                    for condition in symptom_info["conditions"]:
                        disease_name = condition.get("name", "")
                        if "Primary_Symptoms" in condition and isinstance(condition["Primary_Symptoms"], list):
                            for symptom_entry in condition["Primary_Symptoms"]:
                                symptom = symptom_entry.get("Symptom", "")
                                description = symptom_entry.get("Description", "")
                                symptom_writer.writerow([symptom_info["_id"], disease_name, symptom, description])
                # Handle single symptom/description pairs
                else:
                    symptoms_list = condition_data.get("symptoms", [])
                    if isinstance(symptoms_list, list):  # if it is a list we need to parse out the description/symptom for each
                        for symptom_obj in symptoms_list:
                            symptom = symptom_obj.get("symptom", "")
                            description = symptom_obj.get("description", "")
                            symptom_writer.writerow([symptom_info["_id"], disease_name, symptom, description])

    except Exception as e:
        print(f"An error occurred during symptoms CSV writing: {e}")
        return

    print(f"Successfully extracted diseases to {diseases_csv_path}")
    print(f"Successfully extracted symptoms to {symptoms_csv_path}")

if __name__ == "__main__":
    json_file = 'disease_symptoms_data.json'  # Use the provided file name
    diseases_csv = 'diseases.csv'
    symptoms_csv = 'symptoms.csv'
    extract_diseases_and_symptoms(json_file, diseases_csv, symptoms_csv)

from flask import Flask, request, jsonify
import os
import openai
import pandas as pd
from llama_index.core import (  # Import from llama_index.core
    VectorStoreIndex,
    SimpleDirectoryReader,
    ServiceContext,
    StorageContext,
    load_index_from_storage,
    Document,
    get_response_synthesizer,
)
from llama_index.llms.openai import OpenAI
from llama_index.core.text_splitter import TokenTextSplitter  # ✅ Correct Import
#from llama_index.core.text_splitter import RecursiveCharacterTextSplitter  # Option 2
from llama_index.embeddings.openai import OpenAIEmbedding  # ✅ Correct Import
from llama_index.vector_stores.chroma import ChromaVectorStore  # ✅ Correct Import
import chromadb
from llama_index.core.query_engine import RetrieverQueryEngine  # ✅ Correct Import
from llama_index.core.retrievers import VectorIndexRetriever  # ✅ Correct Import
from chromadb.config import Settings # Importing settings for chroma client


app = Flask(__name__)

!pip install langchain-community

!pip install chromadb pandas gradio langchain openai

!pip install langchain-experimental

!pip install --upgrade langchain  # Upgrade LangChain
!pip install langchain-openai

import os
import asyncio
import pandas as pd
from typing import Dict, Any

# Updated imports
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain.schema.runnable import RunnablePassthrough
from langchain.docstore.document import Document
from langchain.retrievers import SelfQueryRetriever
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.prompts import PromptTemplate
from langchain.vectorstores import Chroma
import nest_asyncio

nest_asyncio.apply()

# Securely set OpenAI API key
openai_api_key = os.getenv("OPENAI_API_KEY")
if not openai_api_key:
    raise ValueError("OpenAI API key not found. Set the OPENAI_API_KEY environment variable.")

# User session storage
user_sessions = {}

def build_index():
    """Builds the vector index from CSV files and initializes the retrieval system."""
    try:
        diseases_df = pd.read_csv("diseases.csv")
        symptoms_df = pd.read_csv("symptoms.csv")
        print(f"✅ Loaded diseases.csv ({diseases_df.shape[0]} rows, {diseases_df.shape[1]} columns)")
        print(f"✅ Loaded symptoms.csv ({symptoms_df.shape[0]} rows, {symptoms_df.shape[1]} columns)")
    except Exception as e:
        print(f"❌ CSV Loading Error: {e}")
        return None

    try:
        disease_documents = [
            Document(page_content=f"Disease: {row['disease_name']}. Description: {row.get('description', 'No description available.')}")
            for _, row in diseases_df.iterrows()
        ]
        symptom_documents = [
            Document(page_content=f"Disease: {row['disease_name']}. Symptom: {row['symptom']}. Details: {row.get('description', 'No details available.')}")
            for _, row in symptoms_df.iterrows()
        ]
        all_documents = disease_documents + symptom_documents

        text_splitter = RecursiveCharacterTextSplitter(chunk_size=1024, chunk_overlap=100)
        documents = text_splitter.split_documents(all_documents)
    except Exception as e:
        print(f"❌ Document Processing Error: {e}")
        return None

    try:
        embeddings = OpenAIEmbeddings(openai_api_key=openai_api_key)
        vector_store = Chroma(persist_directory="./chroma_db", embedding_function=embeddings)
        vector_store.add_documents(documents)
        print("✅ Documents embedded and stored successfully in ChromaDB")
    except Exception as e:
        print(f"❌ Vector Store Error: {e}")
        return None

    try:
        llm = ChatOpenAI(model="o3-mini", openai_api_key=openai_api_key)
        retriever = SelfQueryRetriever.from_llm(
            llm, vector_store, "Medical information database", [], search_kwargs={"k": 5}
        )

        prompt = PromptTemplate.from_template("""Given the following context, answer the question:
        {context}

        Question: {question}""")

        # Define the new RunnableSequence for the retrieval chain
        qa_chain = (
            {"context": retriever, "question": RunnablePassthrough()}  # Pass retriever output as context
            | prompt  # Apply prompt template
            | llm  # Pass the structured prompt into LLM
        )

        print("✅ Index built successfully. Retrieval system is active.")
        return qa_chain
    except Exception as e:
        print(f"❌ Query Engine Initialization Error: {e}")
        return None

print("🚀 Building the index...")
query_engine = build_index()
if not query_engine:
    print("❌ Error: Index failed to build. The chatbot will not function correctly.")

async def query_openai(query: str) -> Dict[str, Any]:
    """Runs OpenAI API call asynchronously."""
    if query_engine is None:
        raise ValueError("Query Engine is not initialized. Check if the index was built successfully.")
    return await asyncio.to_thread(query_engine.invoke, query)

async def chatbot(user_input: str):
    """Handles user queries by confirming symptoms before diagnosis."""
    if not query_engine:
        return "Chatbot is unavailable. Index failed to load."
    if not user_input:
        return "No message provided. Please enter your symptoms."

    user_id = "default"
    if user_id in user_sessions and "pending_symptoms" in user_sessions[user_id]:
        confirmed = user_input.lower()
        if "yes" in confirmed:
            symptoms = user_sessions[user_id]["pending_symptoms"]
            del user_sessions[user_id]
            query = f"Based on these symptoms: {symptoms}, what specific diseases are indicated in the database?"
            response = await query_openai(query)
            return f"According to the database:\n{response}"
        elif "no" in confirmed:
            del user_sessions[user_id]
            return "Please enter the correct symptoms."
        else:
            return "Please reply with 'yes' to confirm or 'no' to change symptoms."

    query = f"Based on these symptoms: {user_input}, what possible diseases could this indicate based on the database?"
    response = await query_openai(query)
    user_sessions[user_id] = {"pending_symptoms": user_input}
    return f"From the database:\n{response}\n\nCan you confirm that these are your symptoms? Reply 'yes' or 'no'."

def process_input_sync(user_input):
    """Synchronously processes user input."""
    loop = asyncio.get_event_loop()
    try:
        # Try to get the running loop
        if loop.is_running():
            # If loop is running, create new task and wait for it
            new_loop = asyncio.new_event_loop()
            asyncio.set_event_loop(new_loop)
            response = new_loop.run_until_complete(chatbot(user_input))
            new_loop.close()
            return response
        else:
            return loop.run_until_complete(chatbot(user_input))
    except RuntimeError:
        # Fallback if there's no existing loop
        return asyncio.run(chatbot(user_input))

print("\n🔹 Welcome to the Medical Chatbot! 🔹")
print("Enter your symptoms below and get possible diagnoses. Type 'exit' to stop the chatbot...")

while True:
    user_input = input("You: ")
    if user_input.lower() == "exit":
        print("Chatbot: Goodbye!")
        break
    response = process_input_sync(user_input)
    print(f"Chatbot: {response}")

import os
import asyncio
import pandas as pd
from typing import Dict, Any, Optional
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain.docstore.document import Document
from langchain.retrievers import SelfQueryRetriever
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import Chroma
from langchain.retrievers.self_query.base import AttributeInfo
import nest_asyncio

nest_asyncio.apply()

# Configuration
openai_api_key = os.getenv("OPENAI_API_KEY")
if not openai_api_key:
    raise ValueError("OPENAI_API_KEY environment variable not found")

user_sessions: Dict[str, Dict] = {}

def build_index() -> Optional[SelfQueryRetriever]:
    """Builds and returns the medical knowledge vector index"""
    try:
        # Load and preprocess data
        diseases_df = pd.read_csv("diseases.csv").fillna("")
        symptoms_df = pd.read_csv("symptoms.csv").fillna("")

        # Verify required columns exist
        required_disease_cols = {'disease_name'}
        required_symptom_cols = {'disease_name', 'symptom', 'description'}  # Added description

        if not required_disease_cols.issubset(diseases_df.columns):
            missing = required_disease_cols - set(diseases_df.columns)
            raise ValueError(f"Missing columns in diseases.csv: {missing}")

        if not required_symptom_cols.issubset(symptoms_df.columns):
            missing = required_symptom_cols - set(symptoms_df.columns)
            raise ValueError(f"Missing columns in symptoms.csv: {missing}")

        print(f"✅ Loaded diseases.csv ({len(diseases_df)} entries)")
        print(f"✅ Loaded symptoms.csv ({len(symptoms_df)} entries)")

        # Create documents with description for symptoms
        disease_docs = [
            Document(
                page_content=f"DISEASE: {row['disease_name']}",
                metadata={
                    "type": "disease",
                    "disease_name": row["disease_name"].strip().lower(),
                    "source": "diseases.csv"
                }
            ) for _, row in diseases_df.iterrows()
        ]

        symptom_docs = [
            Document(
                page_content=f"SYMPTOM: {row['symptom']}\nDESCRIPTION: {row['description']}",
                metadata={
                    "type": "symptom",
                    "disease_name": row["disease_name"].strip().lower(),
                    "symptom_name": row["symptom"].strip().lower(),
                    "source": "symptoms.csv"
                }
            ) for _, row in symptoms_df.iterrows()
        ]

        # Rest of the function remains the same...

        # Rest of the build_index function remains the same...

        # Document processing with better chunking
        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=1500,
            chunk_overlap=300,
            keep_separator=True
        )
        all_docs = text_splitter.split_documents(disease_docs + symptom_docs)

        # Vector store setup with validation
        embeddings = OpenAIEmbeddings(openai_api_key=openai_api_key)
        vector_store = Chroma.from_documents(
            documents=all_docs,
            embedding=embeddings,
            persist_directory="./med_db"
        )

        # Enhanced retriever configuration
        metadata_fields = [
            AttributeInfo(
                name="disease_name",
                description="The name of the medical condition",
                type="string",
            ),
            AttributeInfo(
                name="type",
                description="Type of medical data (either 'disease' or 'symptom')",
                type="string",
            )
        ]

        llm = ChatOpenAI(model="o3-mini")
        retriever = SelfQueryRetriever.from_llm(
            llm=llm,
            vectorstore=vector_store,
            document_contents="Medical knowledge database containing diseases and their associated symptoms",
            metadata_field_info=metadata_fields,
            search_kwargs={"k": 10}
        )

        print("✅ Medical knowledge index successfully built")
        return retriever

    except Exception as e:
        print(f"❌ Index construction failed: {e}")
        return None

print("🚀 Initializing medical knowledge system...")
retriever = build_index()

async def query_medical_db(query: str, filter_dict: Optional[Dict] = None) -> str:
    """Executes a medical knowledge query with enhanced filtering"""
    if not retriever:
        return ""

    try:
        docs = await asyncio.to_thread(
            retriever.invoke,
            query,
            filter=filter_dict
        )
        return "\n".join([d.page_content for d in docs[:10]])
    except Exception as e:
        print(f"🔍 Query error: {e}")
        return ""

async def chatbot(user_input: str) -> str:
    """Enhanced diagnosis conversation flow with better symptom handling"""
    if not retriever:
        return "System error: Medical database unavailable"

    user_id = "current_user"
    session = user_sessions.get(user_id, {})
    user_input = user_input.lower().strip()

    # Symptom verification phase
    if "verification_queue" in session:
        if user_input in ("yes", "no"):
            current_symptom = session["current_symptom"]
            if user_input == "yes":
                session["confirmed_symptoms"].append(current_symptom)
                session["confidence"] += 1

            # Get next unique symptom
            while session["verification_queue"]:
                next_symptom = session["verification_queue"].pop(0)
                if next_symptom not in session["processed_symptoms"]:
                    session["current_symptom"] = next_symptom
                    session["processed_symptoms"].add(next_symptom.lower())
                    break
            else:
                # Final diagnosis calculation
                total = session["total_symptoms"]
                confirmed = session["confidence"]
                confidence = min(100, int((confirmed / total) * 100)) if total > 0 else 0

                diagnosis = session["diagnosis"]
                del user_sessions[user_id]
                return (
                    f"Diagnosis Report:\n"
                    f"Condition: {diagnosis}\n"
                    f"Confidence Score: {confidence}%\n"
                    f"Matching Symptoms: {', '.join(session['confirmed_symptoms'])}\n\n"
                    "Note: This is not medical advice. Consult a healthcare professional."
                )

            user_sessions[user_id] = session
            return f"Do you experience: {session['current_symptom']}? (yes/no)"

        return "Please answer 'yes' or 'no' for the current symptom"

    # Initial diagnosis phase
    try:
        # Enhanced initial query
        diagnosis = await query_medical_db(
            f"What diseases could explain these symptoms: {user_input}? "
            f"Return diseases with their associated symptoms.",
            {"type": "disease"}
        )

        if not diagnosis:
            return "No clear diagnosis found. Please consult a doctor."

        # Improved diagnosis parsing
        diagnosis_lines = [line for line in diagnosis.split("\n") if line.strip()]
        disease_info = next(
            (line for line in diagnosis_lines if line.startswith("DISEASE: ")),
            ""
        )
        primary_diagnosis = disease_info.split("DISEASE: ")[1].split("\n")[0].strip()

        # Direct symptom query with exact matching
        symptoms = await query_medical_db(
            f"List all symptoms specifically associated with {primary_diagnosis}",
            {
                "type": "symptom",
                "disease_name": primary_diagnosis.strip().lower()
            }
        )

        # Robust symptom extraction
        symptom_list = []
        seen_symptoms = set()
        for line in symptoms.split("\n"):
            if "SYMPTOM: " in line:
                symptom = line.split("SYMPTOM: ")[1].split("\n")[0].strip()
                symptom_key = symptom.lower()
                if symptom and symptom_key not in seen_symptoms:
                    seen_symptoms.add(symptom_key)
                    symptom_list.append(symptom)

        if not symptom_list:
            # Fallback to alternative symptom search
            symptoms = await query_medical_db(
                f"Find symptoms related to {primary_diagnosis}",
                {"type": "symptom"}
            )
            symptom_list = list(set(
                line.split("SYMPTOM: ")[1].split("\n")[0].strip()
                for line in symptoms.split("\n")
                if "SYMPTOM: " in line
            ))[:5]

        if not symptom_list:
            return f"Potential diagnosis: {primary_diagnosis} (symptom data unavailable)"

        # Initialize verification session
        user_sessions[user_id] = {
            "diagnosis": primary_diagnosis,
            "verification_queue": symptom_list[:7],
            "processed_symptoms": set(),
            "confirmed_symptoms": [],
            "total_symptoms": len(symptom_list[:7]),
            "confidence": 0
        }

        # Start verification process
        first_symptom = user_sessions[user_id]["verification_queue"].pop(0)
        user_sessions[user_id]["current_symptom"] = first_symptom
        user_sessions[user_id]["processed_symptoms"].add(first_symptom.lower())

        return (
            f"Initial Assessment:\n"
            f"Possible Condition: {primary_diagnosis}\n"
            f"First Verification Symptom: {first_symptom}\n"
            "Do you experience this symptom? (yes/no)"
        )

    except Exception as e:
        print(f"⚠️ Diagnosis error: {e}")
        return "Error processing your request. Please try again."

def process_input(user_input: str) -> str:
    """Handles async execution for synchronous input processing"""
    try:
        return asyncio.run(chatbot(user_input))
    except RuntimeError:
        with asyncio.Runner() as runner:
            return runner.run(chatbot(user_input))

if __name__ == "__main__":
    print("\n🩺 Advanced Medical Symptom Analyzer")
    print("Describe your symptoms to begin. Type 'exit' to quit.\n")

    while True:
        try:
            user_input = input("You: ")
            if user_input.lower() in ("exit", "quit"):
                print("System: Thank you for using the medical analyzer. Goodbye!")
                break

            response = process_input(user_input)
            print(f"\nSystem: {response}\n")

        except KeyboardInterrupt:
            print("\nSession terminated by user.")
            break

